### ISSUE TITLE
Cannot execute the test run

### ISSUE THREAD

**Issue by zhuweix** [fiberseq/fiberseq-smk#16]
Cheers,

I am trying to use the fibertools for m6a analysis. I make a fresh mamba environment according to the install.md.
I tested the installation by your test sample:

`
snakemake \
  --profile profile/local  \
  --config \
    env="fiberseq-smk"  \
    test=.test/ccs.bam \
    ref=.test/ref.fa
`

However, I found such error message 

>

> Using profile profile/local for setting default command line arguments.
> /gpfs/gsfs12/users/xuz5/github/fiberseq-smk/workflow/Snakefile:122: SyntaxWarning: invalid escape sequence '\d'
>   # fiber table
> Building DAG of jobs...
> File path ' results/test/test.fiberseq.bam .pbi ' starts with whitespace. This is likely unintended. It can also lead to inconsistent results of the file-matching approach used by Snakemake.
> File path ' results/test/test.fiberseq.bam .pbi ' ends with whitespace. This is likely unintended. It can also lead to inconsistent results of the file-matching approach used by Snakemake.
> File path ' results/test/test.fiberseq.bam .pbi ' starts with whitespace. This is likely unintended. It can also lead to inconsistent results of the file-matching approach used by Snakemake.
> File path ' results/test/test.fiberseq.bam .pbi ' ends with whitespace. This is likely unintended. It can also lead to inconsistent results of the file-matching approach used by Snakemake.
> MissingInputException in rule merge in file /gpfs/gsfs12/users/xuz5/github/fiberseq-smk/workflow/rules/fiberseq-bam.smk, line 175:
> Missing input files for rule merge:
>     output: results/test/test.fiberseq.bam, results/test/test.fiberseq.bam.bai
>     wildcards: sm=test
>     affected files:
>         temp/test/align. 1 -of- 1 .bam

>

I wonder if there is a typo for whitespace in the source code.

**Comment by DavYang** [comment]
I am also experiencing the same issue with the test case.

**Comment by mrvollger** [comment]
We have replaced this pipeline with [ft](https://github.com/fiberseq/fibertools-rs), a binary that replaces this pipeline in a single command!

This note has been added to the readme, and our effort is going to be focused on this new tool.

sorry!
